"""Run the toy decoder or pretrained Qwen2.5 through our own inference engine."""

import argparse

import torch

from .device import resolve_device
from .generation import generate
from .model import ModelConfig, TinyDecoder


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prompt", default="Hello")
    parser.add_argument("--device", choices=("auto", "cpu", "mps", "cuda"), default="auto")
    parser.add_argument("--max-new-tokens", type=int, default=16)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--no-cache", action="store_true")
    parser.add_argument("--full-logits", action="store_true", help="Use the original all-position vocabulary projection")
    rope = parser.add_mutually_exclusive_group()
    rope.add_argument("--share-rope", dest="reuse_rope", action="store_true", help="Experiment with shared RoPE setup (regressed on tested MPS workloads)")
    rope.add_argument("--recompute-rope", dest="reuse_rope", action="store_false", help="Use the default per-application RoPE setup")
    parser.set_defaults(reuse_rope=False)
    parser.add_argument("--model", choices=("tiny", "qwen"), default="tiny")
    parser.add_argument("--context-length", type=int, default=512, help="Context cap for Qwen")
    parser.add_argument("--offline", action="store_true", help="Use only previously cached checkpoint files")
    args = parser.parse_args()
    if not args.prompt or args.max_new_tokens < 0 or args.context_length < 1:
        parser.error("Provide a nonempty prompt, nonnegative output length, and positive context length")
    try:
        device = resolve_device(args.device)
        torch.manual_seed(args.seed)
        torch.set_num_threads(1)
        tokenizer = None
        if args.model == "qwen":
            from .pretrained import load_qwen
            checkpoint = load_qwen(device=device, max_seq_len=args.context_length, local_files_only=args.offline)
            model, tokenizer = checkpoint.model, checkpoint.tokenizer
            ids = tokenizer.encode(args.prompt, add_special_tokens=False)
        else:
            model = TinyDecoder(ModelConfig()).to(device)
            ids = list(args.prompt.encode("utf-8"))
        prompt = torch.tensor([ids], dtype=torch.long, device=device)
        result = generate(model, prompt, args.max_new_tokens, use_cache=not args.no_cache,
                          eos_token_id=tokenizer.eos_token_id if tokenizer else None,
                          last_token_only=not args.full_logits, reuse_rope=args.reuse_rope)
    except ValueError as error:
        parser.error(str(error))
    generated = result[0, prompt.shape[1]:].cpu().tolist()
    print(f"Model={args.model} | device={device} | cache={not args.no_cache} | last-token logits={not args.full_logits}")
    print(f"Shared RoPE frequencies: {args.reuse_rope}")
    print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")
    print(f"Prompt: {args.prompt!r}")
    print(f"Generated token IDs: {generated}")
    if tokenizer:
        print(f"Checkpoint: {checkpoint.model_id}@{checkpoint.revision}")
        print("Completion:", tokenizer.decode(generated, skip_special_tokens=True))
    else:
        print(f"Generated bytes: {bytes(generated)!r}")
        print("Random weights: output demonstrates generation mechanics, not language quality.")


if __name__ == "__main__":
    main()
